In [1]:
%matplotlib inline 
import seaborn as sns
import matplotlib.pyplot as plt
import requests
from bs4 import BeautifulSoup
import tmdbsimple as tmdb
from imdb import IMDb
import numpy as np
import pandas as pd
import time
import cPickle as pickle
import io

In [2]:
MovieTable1 = pd.read_pickle('MovieData100_10_15.pkl')

In [3]:
MDdf = pd.DataFrame(MovieTable1).transpose()
MDdf.head()

,budget,cast,director,genres,gross,id,imdb_id,imdb_rating,mpaa,name,opening_gross,opening_theathers,runtime,year
1865,380000000,"[0000136, 0004851, 0001691, 0574534, 0573618, ...",[0551128],"[Action, Adventure, Fantasy]",241071802,1865,tt1298650,6.7,"Rated PG-13 for sexual content/nudity, languag...",Pirates of the Caribbean: On Stranger Tides,90151958,4155,136,2011
1930,215000000,"[1940449, 1297015, 0406975, 0001459, 0000640, ...",[1989536],"[Action, Adventure]",262030663,1930,tt0948470,7,Rated PG-13 for sequences of action and violence,The Amazing Spider-Man,62004688,4318,136,2012
4258,20000000,"[0864308, 0005350, 3856188, 4795991, 5777210, ...","[0002700, 0001878]",[Comedy],32015787,4258,tt0795461,3.5,Rated PG-13 for crude and sexual content throu...,Scary Movie 5,14157367,3402,86,2013
7978,150000000,"[0581163, 2247629, 1289434, 0001125, 3785649, ...",[0002653],"[Drama, Fantasy, Horror, Thriller]",61979680,7978,tt0780653,5.8,Rated R for bloody horror violence and gore,The Wolfman,31479235,3222,102,2010
9543,150000000,"[0350453, 2605345, 0001426, 0000547, 0869750, ...",[0001565],"[Action, Adventure, Fantasy, Romance]",90759676,9543,tt0473075,6.6,Rated PG-13 for intense sequences of violence ...,Prince of Persia: The Sands of Time,30095259,3646,116,2010

In [4]:
MD_director_gross = MDdf[['director', 'gross']]

In [6]:
director_list = list()
for dl in MD_director_gross.director.get_values():
    if dl == None:
        continue
    for d in dl:
        if d not in director_list:
            director_list.append(d)

In [7]:
director_list

['0551128',
 '1989536',
 '0002700',
 '0001878',
 '0002653',
 '0001565',
 '0000776',
 '0593610',
 '0881279',
 '0796117',
 '0000123',
 '0000217',
 '0946734',
 '0425756',
 '0000229',
 '0504642',
 '0400436',
 '0400441',
 '2676052',
 '0942367',
 '0829820',
 '0525141',
 '0002120',
 '0339030',
 '0501185',
 '0684336',
 '0000255',
 '1207904',
 '0891216',
 '0811583',
 '1720541',
 '0923736',
 '0005509',
 '0855035',
 '0637518',
 '0179221',
 '0570912',
 '0252135',
 '0001060',
 '0831557',
 '0005190',
 '0294457',
 '0000231',
 '1637768',
 '0138620',
 '0001438',
 '0693561',
 '1264352',
 '0506613',
 '1347153',
 '0027271',
 '0935095',
 '0005222',
 '0323239',
 '0455078',
 '0000399',
 '0525659',
 '0003506',
 '0824882',
 '0802248',
 '1079776',
 '0569891',
 '0614682',
 '0178997',
 '0925870',
 '0000881',
 '0585011',
 '0821844',
 '0240797',
 '0075528',
 '0958969',
 '0223359',
 '1224299',
 '0005366',
 '0919369',
 '0908824',
 '0609549',
 '0001752',
 '0679031',
 '0294997',
 '0783536',
 '0160840',
 '0340436',
 '0000127',
 '0108094',
 '0718645',
 '0680846',
 '0000985',
 '0001880',
 '0573732',
 '0235719',
 '0001716',
 '0004716',
 '0001053',
 '0001054',
 '0000165',
 '0000142',
 '0000916',
 '0893659',
 '0616880',
 '0393799',
 '0751102',
 '1512910',
 '0038432',
 '0757858',
 '0142286',
 '3398984',
 '1561257',
 '0601382',
 '1429471',
 '0268370',
 '0268380',
 '2411495',
 '0339004',
 '0634240',
 '0006904',
 '0190859',
 '0001392',
 '0210320',
 '0761498',
 '0229694',
 '0777881',
 '0004056',
 '0629272',
 '0362566',
 '0269463',
 '0853238',
 '1026778',
 '0942504',
 '0174374',
 '0275629',
 '0720135',
 '0809877',
 '0176905',
 '0510912',
 '1164861',
 '1139726',
 '0440458',
 '0617523',
 '0825407',
 '1729171',
 '0009190',
 '0049633',
 '1361017',
 '0833889',
 '0082450',
 '0702797',
 '1349376',
 '0001675',
 '0083348',
 '0015328',
 '0509448',
 '0337773',
 '0553942',
 '0862211',
 '0914134',
 '0005363',
 '2782185',
 '0711840',
 '1856772',
 '0000095',
 '0905592',
 '0000158',
 '0629334',
 '0426059',
 '2482088',
 '0101047',
 '0587955',
 '0103187',
 '1012501',
 '0028764',
 '0152312',
 '0700760',
 '0281508',
 '0768959',
 '0000318',
 '0001747',
 '0333804',
 '0090386',
 '0936482',
 '0525303',
 '0197636',
 '0727754',
 '0520488',
 '0588087',
 '0781842',
 '1053991',
 '0668247',
 '1220140',
 '0075331',
 '2304017',
 '0646515',
 '0004306',
 '0248495',
 '1668276',
 '1103162',
 '2117510',
 '0000233',
 '0088955',
 '0000600',
 '0108132',
 '2616280',
 '0366867',
 '0002657',
 '1375358',
 '1376383',
 '1630273',
 '0373282',
 '0532235',
 '0286975',
 '0520485',
 '0627920',
 '1731937',
 '0288144',
 '1768412',
 '0376006',
 '1302591',
 '1160962',
 '1413364',
 '0719208',
 '0001081',
 '0371890',
 '0566788',
 '0915304',
 '0003160',
 '0186733',
 '0922346',
 '2588606',
 '0851930',
 '0850733',
 '0153078',
 '0428600',
 '2503633',
 '0905154',
 '0905152',
 '1154192',
 '0043742',
 '2752098',
 '0271402',
 '0382956',
 '0097079',
 '0331532',
 '0631473',
 '0702863',
 '0004303',
 '0201509',
 '0970447',
 '3460475',
 '0788202',
 '0001741',
 '0709056',
 '0885864',
 '0867127',
 '1349522',
 '0576298',
 '0281945',
 '0601781',
 '0291205',
 '0213450',
 '0591450',
 '0027572',
 '0000500',
 '1228976',
 '1890845',
 '0000709',
 '0520749',
 '0275698',
 '0031976',
 '1490123',
 '0203002',
 '0000941',
 '0770942',
 '0751577',
 '0751648',
 '0834902',
 '0812307',
 '0524190',
 '0601859',
 '0001338',
 '1793079',
 '0001774',
 '0000386',
 '0298807',
 '0348181',
 '0716257',
 '0888418',
 '3243478',
 '0448831',
 '1625338',
 '2769225',
 '1839743',
 '0615592',
 '0200005',
 '0006846',
 '1119880',
 '0678866',
 '0466349',
 '0589284',
 '0000110',
 '0510731',
 '1361273',
 '1098493',
 '1639277',
 '0359387',
 '0316727',
 '0779433',
 '0000631',
 '0230032',
 '0215455',
 '0885249',
 '0005069',
 '0920274',
 '0026442',
 '1041597',
 '0291082',
 '0030253',
 '0820934',
 '0371755',
 '2320658',
 '0930261',
 '0806492',
 '0220600',
 '2682499',
 '0254120',
 '0001024',
 '0066247',
 '0318916',
 '1226871',
 '1960428',
 '0868219',
 '2926263',
 '0001241',
 '0878763',
 '0871860',
 '1021166',
 '0220240',
 '0482931',
 '3908248',
 '0853374',
 '1616198',
 '0037708',
 '1837748',
 '3230448',
 '1229520',
 '0001401',
 '0484907',
 '2410311',
 '0503259',
 '1196684',
 '0041947',
 '0138927',
 '0863387',
 '1509613',
 '0741262',
 '1634446',
 '1009644',
 '0477129',
 '0141961',
 '5622174',
 '0817895',
 '1757777',
 '0218621',
 '0577647',
 '0002337',
 '0953508',
 '0319659',
 '0312173',
 '0821432',
 '0500610',
 '5507490',
 '0191712',
 '1880561',
 '0481910',
 '0502954',
 '1275670',
 '0270763',
 '2940487',
 '3373074',
 '4949867',
 '4615186',
 '3171597',
 '0564530',
 '0612780',
 '2098823',
 '2466457',
 '2455446',
 '2603848',
 '2559367',
 '1926903',
 '0040734',
 '0084207',
 '2616523',
 '1263285',
 '8367561',
 '8351207',
 '1697560',
 '0294492',
 '0295223',
 '2873575',
 '8377173',
 '4700496',
 '5351657',
 '2795771',
 '3196241',
 '3889830',
 '4664099',
 '5074519',
 '3374111',
 '1086005',
 '1380806',
 '2660380',
 '2749141',
 '3413313',
 '3413977',
 '1739457',
 '3364004',
 '1543633',
 '2566169',
 '1890588',
 '8367562',
 '3983968',
 '2655289',
 '0797520',
 '1892658',
 '4680110',
 '2682257',
 '3380929',
 '2936815',
 '1218281',
 '4932106',
 '1654417',
 '2967350',
 '4733595',
 '8351208',
 '3095427',
 '0006969',
 '1043295',
 '0179697',
 '1000113',
 '0065608',
 '3331401',
 '0414423',
 '1016428',
 '0006960',
 '5571836',
 '1847738',
 '0945026',
 '0898288',
 '0001129',
 '0336620',
 '0528963',
 '0300174',
 '1191481',
 '0327944',
 '2031205',
 '1164602',
 '5993360',
 '1500577',
 '0342638',
 '1767218',
 '0815541',
 '4000389',
 '3951039',
 '0193508',
 '1270033',
 '5757355',
 '1378517',
 '1531914',
 '0565336',
 '7455081',
 '1310861',
 '1481618',
 '3191729',
 '1382072',
 '0649609',
 '0776720',
 '0841923',
 '5905424',
 '0625458',
 '0932766',
 '7178585',
 '0062357',
 '2344139',
 '5036592',
 '5615480',
 '0923959',
 '2096009',
 '0140087',
 '0781673',
 '0226335',
 '3990253',
 '6876267',
 '2091911',
 '0559251',
 '4663399',
 '0288188',
 '7667960',
 '0179018']

In [12]:
dd = dict()
for d in director_list:
    tl = list()
    for gg in MD_director_gross.director:
        if gg == None:
            tl.append(False)
        else:
            tl.append(d in gg)
    dd[d] = MD_director_gross[tl].gross

In [15]:
for director in dd.keys():
    print dd[director]
    print '*******************'

46529    55100437
Name: gross, dtype: object
*******************
35056      98711404
39254      85468508
116741     44672764
181533    113746621
239678     34296320
Name: gross, dtype: object
*******************
64328     88631237
145220    51183113
Name: gross, dtype: object
*******************
324471    50856010
Name: gross, dtype: object
*******************
226486    84525432
Name: gross, dtype: object
*******************
68724     93050117
198184    31569268
Name: gross, dtype: object
*******************
82690    189422889
Name: gross, dtype: object
*******************
54138    228778661
Name: gross, dtype: object
*******************
50646     84351197
256591    53862963
Name: gross, dtype: object
*******************
286565    32000304
Name: gross, dtype: object
*******************
87825    35763137
Name: gross, dtype: object
*******************
227783    64251541
Name: gross, dtype: object
*******************
50456    40259119
Name: gross, dtype: object
*******************
50348    58009200
Name: gross, dtype: object
*******************
333348    26302731
Name: gross, dtype: object
*******************
38358    41034350
Name: gross, dtype: object
*******************
45269    135453143
82695    148809770
Name: gross, dtype: object
*******************
52520    62321039
Name: gross, dtype: object
*******************
227348    32462372
Name: gross, dtype: object
*******************
77174    56003051
Name: gross, dtype: object
*******************
53182    106580051
Name: gross, dtype: object
*******************
23048     50287556
222899    48637684
243938    81476385
Name: gross, dtype: object
*******************
145316    191452396
Name: gross, dtype: object
*******************
107811    25682380
Name: gross, dtype: object
*******************
49524      33618855
262500    130179072
Name: gross, dtype: object
*******************
41439    45710178
Name: gross, dtype: object
*******************
257091    90411453
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
56292    209397903
Name: gross, dtype: object
*******************
328556    52076908
Name: gross, dtype: object
*******************
76203    56671993
Name: gross, dtype: object
*******************
283445    27740955
Name: gross, dtype: object
*******************
72190    202359711
Name: gross, dtype: object
*******************
44048    81562942
Name: gross, dtype: object
*******************
249164    50474843
Name: gross, dtype: object
*******************
81969    149260504
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
57165     83670083
98566    191204754
Name: gross, dtype: object
*******************
225565    26068955
Name: gross, dtype: object
*******************
293863    42629776
Name: gross, dtype: object
*******************
41515    100246011
Name: gross, dtype: object
*******************
72570    125014030
Name: gross, dtype: object
*******************
228205    37446117
Name: gross, dtype: object
*******************
20526    172062763
Name: gross, dtype: object
*******************
44040    33601190
Name: gross, dtype: object
*******************
65086    54333290
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
64635    58877969
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
34803    42739347
Name: gross, dtype: object
*******************
42888    30212620
Name: gross, dtype: object
*******************
11324     128012934
44826      73864507
106646    116900694
Name: gross, dtype: object
*******************
83666     45512466
120467    59301324
Name: gross, dtype: object
*******************
85446    35074677
Name: gross, dtype: object
*******************
277216    161197785
Name: gross, dtype: object
*******************
48988     45060734
100042    86208010
Name: gross, dtype: object
*******************
32823    60974475
72207    28835528
Name: gross, dtype: object
*******************
137094     50577412
150689    201151353
Name: gross, dtype: object
*******************
72197    31051126
Name: gross, dtype: object
*******************
243940    25801047
Name: gross, dtype: object
*******************
229405    368061265
Name: gross, dtype: object
*******************
27573    67061228
Name: gross, dtype: object
*******************
35791    60128566
71679    42345531
Name: gross, dtype: object
*******************
72334    28972764
Name: gross, dtype: object
*******************
254843    32172757
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
241958    61002302
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
38167    80574010
Name: gross, dtype: object
*******************
435092    42340598
Name: gross, dtype: object
*******************
245891    43037835
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
71688    30017992
Name: gross, dtype: object
*******************
77951    36076121
Name: gross, dtype: object
*******************
314365    45055776
Name: gross, dtype: object
*******************
336592    188020017
Name: gross, dtype: object
*******************
169917    26307600
Name: gross, dtype: object
*******************
65759    64006466
Name: gross, dtype: object
*******************
304357    33307793
Name: gross, dtype: object
*******************
4258      32015787
146304    70525195
Name: gross, dtype: object
*******************
109428    54239856
Name: gross, dtype: object
*******************
27576     118311368
227156     45090374
Name: gross, dtype: object
*******************
272693    34030343
Name: gross, dtype: object
*******************
82687     37134215
268920    34580201
Name: gross, dtype: object
*******************
188222    32363404
Name: gross, dtype: object
*******************
38365     162001186
50546     103028109
71880      74158157
109418    133668525
Name: gross, dtype: object
*******************
355499    47425125
Name: gross, dtype: object
*******************
77174    56003051
Name: gross, dtype: object
*******************
87428      36931089
227159     54445357
274167    150357137
Name: gross, dtype: object
*******************
321741    34542474
Name: gross, dtype: object
*******************
20504    94835059
Name: gross, dtype: object
*******************
87502    93772375
Name: gross, dtype: object
*******************
80585    38518613
Name: gross, dtype: object
*******************
62213    79727149
62214    35291068
Name: gross, dtype: object
*******************
139038    40041683
Name: gross, dtype: object
*******************
122544    53261944
Name: gross, dtype: object
*******************
76494    41152203
Name: gross, dtype: object
*******************
57119    37295394
Name: gross, dtype: object
*******************
62177    237283207
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
65759    64006466
Name: gross, dtype: object
*******************
235260    59700064
Name: gross, dtype: object
*******************
38745     42779261
257445    80080379
Name: gross, dtype: object
*******************
355309    228433663
Name: gross, dtype: object
*******************
49040    113203870
Name: gross, dtype: object
*******************
64686    38362475
Name: gross, dtype: object
*******************
34016    32010860
Name: gross, dtype: object
*******************
70115    26593646
Name: gross, dtype: object
*******************
75780      80070736
177677    195042377
Name: gross, dtype: object
*******************
100402    259766572
Name: gross, dtype: object
*******************
198185    36457627
Name: gross, dtype: object
*******************
12444    295983305
12445    381011219
Name: gross, dtype: object
*******************
64688     138447667
137106    257760692
187017    191719337
Name: gross, dtype: object
*******************
49519    187168425
Name: gross, dtype: object
*******************
152737    37738810
Name: gross, dtype: object
*******************
228496    38543473
Name: gross, dtype: object
*******************
44603      32746941
88794      37306030
190859    350126372
209451     47047013
Name: gross, dtype: object
*******************
147441    65014513
Name: gross, dtype: object
*******************
158011    51872378
Name: gross, dtype: object
*******************
177572    222527828
Name: gross, dtype: object
*******************
136400    75612460
Name: gross, dtype: object
*******************
17578     77591831
57212     79884879
296098    72313754
Name: gross, dtype: object
*******************
48988     45060734
100042    86208010
Name: gross, dtype: object
*******************
41233     42400223
54518     73013910
72559    122523060
Name: gross, dtype: object
*******************
449154    36665854
Name: gross, dtype: object
*******************
107811    25682380
Name: gross, dtype: object
*******************
406054    65001093
Name: gross, dtype: object
*******************
24428    623357910
Name: gross, dtype: object
*******************
134411    42930462
Name: gross, dtype: object
*******************
117251    73103784
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
38050    62495645
Name: gross, dtype: object
*******************
80321    216391482
Name: gross, dtype: object
*******************
29427     39123589
274854    27367660
Name: gross, dtype: object
*******************
37834    76423035
Name: gross, dtype: object
*******************
65291    116601172
Name: gross, dtype: object
*******************
22894    40168080
Name: gross, dtype: object
*******************
38322    37915414
Name: gross, dtype: object
*******************
264999    66013057
Name: gross, dtype: object
*******************
57431    30441326
Name: gross, dtype: object
*******************
13477    32680633
Name: gross, dtype: object
*******************
38408    53374681
Name: gross, dtype: object
*******************
254470    184296230
Name: gross, dtype: object
*******************
45317      93617009
82693     132092958
168672    150117807
Name: gross, dtype: object
*******************
205596    91125683
Name: gross, dtype: object
*******************
76800    33047633
Name: gross, dtype: object
*******************
307108    159582188
Name: gross, dtype: object
*******************
249070    22467450
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
34806    37490007
Name: gross, dtype: object
*******************
89492      67544505
271718    110212700
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
186190    48086903
Name: gross, dtype: object
*******************
23437    63075011
Name: gross, dtype: object
*******************
23023    60022256
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
54553    251513985
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
38579    33644788
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
39513    37412945
Name: gross, dtype: object
*******************
388998    43787265
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
51540     117538559
109431    134506920
Name: gross, dtype: object
*******************
91586      83586447
138843    137400141
168259    353007020
Name: gross, dtype: object
*******************
252882    119793567
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
118340    333176600
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
132232    71628180
Name: gross, dtype: object
*******************
80321    216391482
Name: gross, dtype: object
*******************
239563    44137712
Name: gross, dtype: object
*******************
227719    22348241
Name: gross, dtype: object
*******************
71552    57011521
Name: gross, dtype: object
*******************
273481    46889293
Name: gross, dtype: object
*******************
38055    148415853
80321    216391482
Name: gross, dtype: object
*******************
249660    60755732
Name: gross, dtype: object
*******************
62206    37053924
82682    46000903
Name: gross, dtype: object
*******************
72213     34522221
323272    67790117
Name: gross, dtype: object
*******************
44833    65422625
Name: gross, dtype: object
*******************
385622    35353000
Name: gross, dtype: object
*******************
325231    200676069
Name: gross, dtype: object
*******************
55721     169106725
238713    110825712
Name: gross, dtype: object
*******************
10140    104386950
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
216529    56117548
Name: gross, dtype: object
*******************
77883    49130154
Name: gross, dtype: object
*******************
304372    57027435
Name: gross, dtype: object
*******************
59967    66486205
Name: gross, dtype: object
*******************
64956    292576195
Name: gross, dtype: object
*******************
1930      262030663
102382    202853933
Name: gross, dtype: object
*******************
62177    237283207
Name: gross, dtype: object
*******************
62177    237283207
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
39451    148438600
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
60308    75605492
Name: gross, dtype: object
*******************
214570    35266619
Name: gross, dtype: object
*******************
252838    64460211
Name: gross, dtype: object
*******************
35019    29011215
Name: gross, dtype: object
*******************
10193    415004880
Name: gross, dtype: object
*******************
10192     238736787
55301     133110742
228165    162994032
Name: gross, dtype: object
*******************
38575     176591618
123553     31165421
Name: gross, dtype: object
*******************
228176    26766213
Name: gross, dtype: object
*******************
198663    102427862
294254     81697192
Name: gross, dtype: object
*******************
76757    47387723
Name: gross, dtype: object
*******************
76757    47387723
Name: gross, dtype: object
*******************
314106    26627201
Name: gross, dtype: object
*******************
55465    35061031
Name: gross, dtype: object
*******************
56288    38538188
Name: gross, dtype: object
*******************
288210    39440655
Name: gross, dtype: object
*******************
37958    83504017
62764    64935167
Name: gross, dtype: object
*******************
122544    53261944
Name: gross, dtype: object
*******************
51497    209837675
82992    238679850
Name: gross, dtype: object
*******************
98948    182207973
Name: gross, dtype: object
*******************
10196    131772187
82700     60522097
Name: gross, dtype: object
*******************
242500    67631157
Name: gross, dtype: object
*******************
117263     98925640
156022    101530738
307081     52421953
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
37821    47059963
Name: gross, dtype: object
*******************
27581      44875481
109443    125168368
318846     70259870
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
55787      58709717
101299    424668047
131631    337135885
131634    281723902
Name: gross, dtype: object
*******************
37724     304360277
206647    200074609
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
228203    44482410
Name: gross, dtype: object
*******************
299245    22764410
Name: gross, dtype: object
*******************
170687    50837305
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
44992    51828677
Name: gross, dtype: object
*******************
119450    208545589
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
64682    144840419
Name: gross, dtype: object
*******************
73723    214030500
Name: gross, dtype: object
*******************
77016    41003371
Name: gross, dtype: object
*******************
283807    53262560
Name: gross, dtype: object
*******************
258509    85886987
Name: gross, dtype: object
*******************
282675    37400127
Name: gross, dtype: object
*******************
72105     218815487
188161     43139300
Name: gross, dtype: object
*******************
268238    33078266
Name: gross, dtype: object
*******************
116745    58236838
Name: gross, dtype: object
*******************
164558    28873374
Name: gross, dtype: object
*******************
229405    368061265
Name: gross, dtype: object
*******************
20504    94835059
Name: gross, dtype: object
*******************
48138     63686397
241554    26461644
Name: gross, dtype: object
*******************
423971    334191110
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
218778    66954149
Name: gross, dtype: object
*******************
49051     303003568
57158     258366855
122917    255119788
Name: gross, dtype: object
*******************
268374    131538435
Name: gross, dtype: object
*******************
314571    37880356
Name: gross, dtype: object
*******************
43959    43853424
Name: gross, dtype: object
*******************
76492     148313048
159824    169700110
Name: gross, dtype: object
*******************
7978    61979680
Name: gross, dtype: object
*******************
214570    35266619
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
227306    115637895
Name: gross, dtype: object
*******************
211449    42025135
Name: gross, dtype: object
*******************
68728    234911825
Name: gross, dtype: object
*******************
37786    95347692
Name: gross, dtype: object
*******************
250546    84273813
Name: gross, dtype: object
*******************
238603    38934842
Name: gross, dtype: object
*******************
136331    57884114
Name: gross, dtype: object
*******************
137113    100206256
Name: gross, dtype: object
*******************
138741    126477084
Name: gross, dtype: object
*******************
33909     52474616
388880    47382068
Name: gross, dtype: object
*******************
68718     162805434
273248     54117416
Name: gross, dtype: object
*******************
184346    30577122
Name: gross, dtype: object
*******************
254251    58607007
Name: gross, dtype: object
*******************
299245    22764410
Name: gross, dtype: object
*******************
75810    37300107
Name: gross, dtype: object
*******************
80355    52000688
Name: gross, dtype: object
*******************
232679    30127963
Name: gross, dtype: object
*******************
132363    116632095
Name: gross, dtype: object
*******************
33217    64003625
76285    68559554
Name: gross, dtype: object
*******************
61791     176760185
284536     33680992
Name: gross, dtype: object
*******************
38357    31011732
Name: gross, dtype: object
*******************
40264    36661504